// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogsDocumentDataSlicesSlice = BlogContentSectionSlice;

/**
 * Content for Blogs documents
 */
interface BlogsDocumentData {
  /**
   * Title field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Writer field in *Blogs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.writer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  writer: prismic.ContentRelationshipField<"writer">;

  /**
   * Slice Zone field in *Blogs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blogs document from Prismic
 *
 * - **API ID**: `blogs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogsDocumentData>, "blogs", Lang>;

/**
 * Item in *Categorized Navigation → Nav Group*
 */
export interface CategorizedNavigationDocumentDataNavGroupItem {
  /**
   * Items field in *Categorized Navigation → Nav Group*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: categorized_navigation.nav_group[].items
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  items: prismic.ContentRelationshipField<"navigation_group">;
}

/**
 * Content for Categorized Navigation documents
 */
interface CategorizedNavigationDocumentData {
  /**
   * Nav Group field in *Categorized Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categorized_navigation.nav_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_group: prismic.GroupField<
    Simplify<CategorizedNavigationDocumentDataNavGroupItem>
  >;
}

/**
 * Categorized Navigation document from Prismic
 *
 * - **API ID**: `categorized_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategorizedNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CategorizedNavigationDocumentData>,
    "categorized_navigation",
    Lang
  >;

/**
 * Item in *Course → Parent Lesson List*
 */
export interface CourseDocumentDataParentLessonListItem {
  /**
   * Lesson field in *Course → Parent Lesson List*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: course.parent_lesson_list[].lesson
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lesson: prismic.ContentRelationshipField<"lesson" | "lesson_group">;
}

type CourseDocumentDataSlicesSlice = BlogContentSectionSlice;

/**
 * Content for Course documents
 */
interface CourseDocumentData {
  /**
   * Title field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Parent Lesson List field in *Course*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: course.parent_lesson_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  parent_lesson_list: prismic.GroupField<
    Simplify<CourseDocumentDataParentLessonListItem>
  >;

  /**
   * Writer field in *Course*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: course.writer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  writer: prismic.ContentRelationshipField<"writer">;

  /**
   * Slice Zone field in *Course*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: course.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CourseDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: course.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Course*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: course.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Course*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: course.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Course document from Prismic
 *
 * - **API ID**: `course`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CourseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CourseDocumentData>, "course", Lang>;

type HomepageDocumentDataSlicesSlice =
  | CallToActionSectionSlice
  | FaqSectionSlice
  | MotivationalSliceSlice
  | HeroSectionSlice
  | HeroTextSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type LessonDocumentDataSlicesSlice = BlogContentSectionSlice;

/**
 * Content for Lesson documents
 */
interface LessonDocumentData {
  /**
   * Title field in *Lesson*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Lesson*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LessonDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Lesson*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: lesson.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Lesson*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Lesson*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: lesson.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Lesson document from Prismic
 *
 * - **API ID**: `lesson`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LessonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LessonDocumentData>, "lesson", Lang>;

/**
 * Item in *Lesson Group → Lesson List*
 */
export interface LessonGroupDocumentDataLessonListItem {
  /**
   * Lesson field in *Lesson Group → Lesson List*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson_group.lesson_list[].lesson
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lesson: prismic.ContentRelationshipField<"lesson">;
}

/**
 * Content for Lesson Group documents
 */
interface LessonGroupDocumentData {
  /**
   * Title field in *Lesson Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson_group.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Lesson List field in *Lesson Group*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: lesson_group.lesson_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  lesson_list: prismic.GroupField<
    Simplify<LessonGroupDocumentDataLessonListItem>
  >;
}

/**
 * Lesson Group document from Prismic
 *
 * - **API ID**: `lesson_group`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LessonGroupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LessonGroupDocumentData>,
    "lesson_group",
    Lang
  >;

type MarketingPageDocumentDataSlicesSlice = never;

/**
 * Content for Marketing Page documents
 */
interface MarketingPageDocumentData {
  /**
   * Slice Zone field in *Marketing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MarketingPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Marketing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: marketing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Marketing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Marketing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: marketing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Marketing Page document from Prismic
 *
 * - **API ID**: `marketing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MarketingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MarketingPageDocumentData>,
    "marketing_page",
    Lang
  >;

/**
 * Item in *Navigation → Nav Group*
 */
export interface NavigationDocumentDataNavGroupItem {
  /**
   * Nav Label field in *Navigation → Nav Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_group[].nav_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nav_label: prismic.KeyTextField;

  /**
   * Nav Link field in *Navigation → Nav Group*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_group[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.ContentRelationshipField<"marketing_page" | "homepage">;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Nav Group field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_group: prismic.GroupField<Simplify<NavigationDocumentDataNavGroupItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Item in *Navigation Group → Navigations*
 */
export interface NavigationGroupDocumentDataNavigationsItem {
  /**
   * Label field in *Navigation Group → Navigations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_group.navigations[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation Group → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_group.navigations[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation Group documents
 */
interface NavigationGroupDocumentData {
  /**
   * Group Label field in *Navigation Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_group.group_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_label: prismic.KeyTextField;

  /**
   * Navigations field in *Navigation Group*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_group.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigations: prismic.GroupField<
    Simplify<NavigationGroupDocumentDataNavigationsItem>
  >;
}

/**
 * Navigation Group document from Prismic
 *
 * - **API ID**: `navigation_group`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationGroupDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationGroupDocumentData>,
    "navigation_group",
    Lang
  >;

/**
 * Content for Writer documents
 */
interface WriterDocumentData {
  /**
   * Name field in *Writer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: writer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Writer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: writer.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Company field in *Writer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: writer.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;
}

/**
 * Writer document from Prismic
 *
 * - **API ID**: `writer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WriterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WriterDocumentData>, "writer", Lang>;

export type AllDocumentTypes =
  | BlogsDocument
  | CategorizedNavigationDocument
  | CourseDocument
  | HomepageDocument
  | LessonDocument
  | LessonGroupDocument
  | MarketingPageDocument
  | NavigationDocument
  | NavigationGroupDocument
  | WriterDocument;

/**
 * Primary content in *ContentSection → Primary*
 */
export interface BlogContentSectionSliceDefaultPrimary {
  /**
   * Section Title field in *ContentSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Primary content in *ContentSection → Items*
 */
export interface BlogContentSectionSliceDefaultItem {
  /**
   * Image field in *ContentSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ContentSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content_section.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContentSectionSliceDefaultPrimary>,
  Simplify<BlogContentSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ContentSection*
 */
type BlogContentSectionSliceVariation = BlogContentSectionSliceDefault;

/**
 * ContentSection Shared Slice
 *
 * - **API ID**: `blog_content_section`
 * - **Description**: BlogContentSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentSectionSlice = prismic.SharedSlice<
  "blog_content_section",
  BlogContentSectionSliceVariation
>;

/**
 * Primary content in *CallToActionSection → Primary*
 */
export interface CallToActionSectionSliceDefaultPrimary {
  /**
   * Title field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Primary Buton Label field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.primary_buton_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_buton_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * Secondary Button Label field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Default variation for CallToActionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToActionSection → Primary*
 */
export interface CallToActionSectionSliceOneButtonPrimary {
  /**
   * Title field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Primary Buton Label field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.primary_buton_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_buton_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *CallToActionSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_section.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;
}

/**
 * One Button variation for CallToActionSection Slice
 *
 * - **API ID**: `oneButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSectionSliceOneButton = prismic.SharedSliceVariation<
  "oneButton",
  Simplify<CallToActionSectionSliceOneButtonPrimary>,
  never
>;

/**
 * Slice variation for *CallToActionSection*
 */
type CallToActionSectionSliceVariation =
  | CallToActionSectionSliceDefault
  | CallToActionSectionSliceOneButton;

/**
 * CallToActionSection Shared Slice
 *
 * - **API ID**: `call_to_action_section`
 * - **Description**: CallToActionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSectionSlice = prismic.SharedSlice<
  "call_to_action_section",
  CallToActionSectionSliceVariation
>;

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Question field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *TextSection → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Hero Title field in *TextSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Description field in *TextSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextSection → Primary*
 */
export interface HeroSectionSliceCtaButtonPrimary {
  /**
   * Hero Title field in *TextSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Description field in *TextSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Link field in *TextSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *TextSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * CTA Button variation for TextSection Slice
 *
 * - **API ID**: `ctaButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceCtaButton = prismic.SharedSliceVariation<
  "ctaButton",
  Simplify<HeroSectionSliceCtaButtonPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceCtaButton;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroTextSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Primary Buton Label field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.primary_buton_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_buton_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *HeroSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * Secondary Button Label field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *HeroSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroTextSliceNoButtonPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * No Button variation for HeroSection Slice
 *
 * - **API ID**: `noButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceNoButton = prismic.SharedSliceVariation<
  "noButton",
  Simplify<HeroTextSliceNoButtonPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroTextSliceTitleOnlyPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Title Only variation for HeroSection Slice
 *
 * - **API ID**: `titleOnly`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceTitleOnly = prismic.SharedSliceVariation<
  "titleOnly",
  Simplify<HeroTextSliceTitleOnlyPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroTextSliceCenteredPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_text.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Centered variation for HeroSection Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<HeroTextSliceCenteredPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroTextSliceVariation =
  | HeroTextSliceDefault
  | HeroTextSliceNoButton
  | HeroTextSliceTitleOnly
  | HeroTextSliceCentered;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_text`
 * - **Description**: HeroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSlice = prismic.SharedSlice<
  "hero_text",
  HeroTextSliceVariation
>;

/**
 * Primary content in *MotivationalSlice → Primary*
 */
export interface MotivationalSliceSliceDefaultPrimary {
  /**
   * Title field in *MotivationalSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: motivational_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for MotivationalSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MotivationalSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MotivationalSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MotivationalSlice*
 */
type MotivationalSliceSliceVariation = MotivationalSliceSliceDefault;

/**
 * MotivationalSlice Shared Slice
 *
 * - **API ID**: `motivational_slice`
 * - **Description**: MotivationalSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MotivationalSliceSlice = prismic.SharedSlice<
  "motivational_slice",
  MotivationalSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogsDocument,
      BlogsDocumentData,
      BlogsDocumentDataSlicesSlice,
      CategorizedNavigationDocument,
      CategorizedNavigationDocumentData,
      CategorizedNavigationDocumentDataNavGroupItem,
      CourseDocument,
      CourseDocumentData,
      CourseDocumentDataParentLessonListItem,
      CourseDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LessonDocument,
      LessonDocumentData,
      LessonDocumentDataSlicesSlice,
      LessonGroupDocument,
      LessonGroupDocumentData,
      LessonGroupDocumentDataLessonListItem,
      MarketingPageDocument,
      MarketingPageDocumentData,
      MarketingPageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavGroupItem,
      NavigationGroupDocument,
      NavigationGroupDocumentData,
      NavigationGroupDocumentDataNavigationsItem,
      WriterDocument,
      WriterDocumentData,
      AllDocumentTypes,
      BlogContentSectionSlice,
      BlogContentSectionSliceDefaultPrimary,
      BlogContentSectionSliceDefaultItem,
      BlogContentSectionSliceVariation,
      BlogContentSectionSliceDefault,
      CallToActionSectionSlice,
      CallToActionSectionSliceDefaultPrimary,
      CallToActionSectionSliceOneButtonPrimary,
      CallToActionSectionSliceVariation,
      CallToActionSectionSliceDefault,
      CallToActionSectionSliceOneButton,
      FaqSectionSlice,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceCtaButtonPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceCtaButton,
      HeroTextSlice,
      HeroTextSliceDefaultPrimary,
      HeroTextSliceNoButtonPrimary,
      HeroTextSliceTitleOnlyPrimary,
      HeroTextSliceCenteredPrimary,
      HeroTextSliceVariation,
      HeroTextSliceDefault,
      HeroTextSliceNoButton,
      HeroTextSliceTitleOnly,
      HeroTextSliceCentered,
      MotivationalSliceSlice,
      MotivationalSliceSliceDefaultPrimary,
      MotivationalSliceSliceVariation,
      MotivationalSliceSliceDefault,
    };
  }
}
