// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_content_section: dynamic(() => import("./ContentSection")),
  hero_section: dynamic(() => import("./TextSection")),
  hero_text: dynamic(() => import("./HeroSection")),
  motivational_slice: dynamic(() => import("./MotivationalSlice")),
};
