// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_content_section: dynamic(() => import("./ContentSection")),
  call_to_action_section: dynamic(() => import("./CallToActionSection")),
  faq_section: dynamic(() => import("./FaqSection")),
  hero_text: dynamic(() => import("./HeroSection")),
  motivational_slice: dynamic(() => import("./MotivationalSection")),
};
